# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(max_length=255)),
                ('account_number', models.IntegerField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bankdetails')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.persondetails')),
            ],
        ),
    ]
