# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180311_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='account_number',
        ),
    ]
