# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accountdetails_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Bankdetails'),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Persondetails'),
        ),
    ]
