# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan', '0007_auto_20180314_0552'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loandata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_date', models.DateField(auto_now_add=True)),
                ('payable_amount', models.IntegerField()),
                ('payable_status', models.CharField(max_length=255)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Loandetails')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Persondetails')),
            ],
        ),
    ]
