# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loandetails', '0004_auto_20180318_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandata',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Loandetails'),
        ),
        migrations.AlterField(
            model_name='loandata',
            name='payable_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loandata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Persondetails'),
        ),
    ]
